### ISSUE TITLE
unclear documentation

### ISSUE THREAD

**Issue by smokes2345** [Spiritdude/Slicer4RTN#1]
It isn't clear how to enable conical slices.  I've got the slicer working with prusa-slicer, but i seem to be getting tilted slices instead of conical slices and i'm not sure why.

**Comment by Spiritdude** [comment]
Provide more details, e.g. list of settings as listed in the resulting gcode.

**Comment by smokes2345** [comment]
the command i'm using:

` ./slicer3rtn overhang-out.stl --angle=8 --axis=3 --load=AllSpark.ini --load=Wood\ PLA\ \@CREALITY.ini --load=0.16mm\ OPTIMAL\ \@CREALITY\ -\ Copy.ini --slicer="./prusa-slicer-console.exe" -v --center=127,127 --bed-center=127,127 --recenter`

I added the `--center`, `--bed-center`, and `--recenter` options after my first couple of test prints to try and make sure my print was in the middle of the bed/cone.

and here's the "settings" section of the gcode

```
; == Slicer4RTN 0.4.7 == https://github.com/Spiritdude/Slicer4RTN
; Date: Wed Apr 28 16:33:16 2021
; Settings:
;   angle = 8
;   axis = 3
;   bed_center = 127,127
;   center = 127,127
;   efmax = 3
;   efmin = 0.01
;   erate = 1
;   inter_steps = 2
;   keep = 0
;   layer_height = 0.2
;   max_speed = 0
;   mode = outside
;   motion_minz = 0.2
;   recenter = 1
;   rot_gcode = A
;   rot_offset = -90
;   rot_revolv = 1
;   slicer = ./prusa-slicer-console.exe
;   subdivide = 2
;   tilt_gcode = B
;   verbose = 1
;   zoff = 0
; Slicer-specific settings: '--gcode-comments' '--skirts=0' '--center=0,0' '-s' '--layer-height=0.201965514503724' '--load=AllSpark.ini' '--load=Wood PLA @CREALITY.ini' '--load=0.16mm OPTIMAL @CREALITY - Copy.ini'
;
; generated by PrusaSlicer 2.3.0+win64 on 2021-04-28 at 20:33:09 UTC

;

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm
```

**Comment by smokes2345** [comment]
i realize the "angle" is *really* low, when i have more time i plan on removing my cooling fan and trying more prints with a steeper angle.

**Comment by Spiritdude** [comment]
`--axis=3` means, you have no rotating 4th axis, this falls back to tilted slices, remove `--axis=3` or do `--axis=4` (default). You assume you want to print conic slices with a 3-axis FDM, this means, you must create 4-axis G-code but firmware ignores the rotation angle of the nozzle, and yes keep the angle low, e.g. 25 deg, move the part cooler up etc avoid `prusa-slicer` as it fails to slice conic projected models needed for conic slicing before projecting back.

**Comment by smokes2345** [comment]
well this is pretty awesome, great work and thanks for sharing.  i've still got the nozzle trying to print in open space, but i think that might be because i still have a very low angle.  I'm going to play with my cooling fan/duct and play with slightly steeper angles.
