### ISSUE TITLE
Where is the home location of the rotational axis?

### ISSUE THREAD

**Issue by jan3ll3** [Spiritdude/Slicer4RTN#10]
I built a RotBot from a slightly modified version of the ZHAW design. 

What angle is the machine's home (zero) supposed to be for the rotational axis?

**Comment by Spiritdude** [comment]
See usage output of slicer4rtn:
```
 --rot-offset=<a>     set rotation offset (default: -90)
```
and also the documentation I wrote at https://xyzdims.com/3d-printing/slicer4rtn/
