### ISSUE TITLE
transforms in slicer cause adjusted "layers" to warp

### ISSUE THREAD

**Issue by smokes2345** [Spiritdude/Slicer4RTN#2]
[slicer4rtn_warped.zip](https://github.com/Spiritdude/Slicer4RTN/files/6460682/slicer4rtn_warped.zip)
a few prints are oriented for traditional supports and bridges, where conical slices might eliminate such need.  however, using transforms in the slicer (such as --rotate-x) seem to cause warping of the object after the conical slices are applied.

I've included the original STL, final gcode and both temp files in the attached zip file.  These files were generated with the command: ` ./slicer3rtn --angle=8 --load=AllSpark.ini --load=0.16mm\ OPTIMAL\ \@CREALITY\ -\ Copy.ini --slicer="./prusa-slicer-console.exe" --load=TPU.ini /cygdrive/c/Users/matt/Downloads/POD4560.stl --recenter --mode=outside --rotate-x=270 --rotate-y=315 --rotate=90 --z-offset=46.94 -k`

I got the numbers for the rotate and offset values by loading the STL in prusaslicer GUI, making the transforms and copying the numbers over.

REALLY loving this idea, i know its still *very* new, but i've been printing a ton of stuff with slicer4rtn lately on my mostly stock ender3, this thing is pretty amazing.  being able to eliminate supports is awesome, particularly when dealing with TPU, i don't know anybody that likes supports lol

**Comment by Spiritdude** [comment]
Don't transform in the core-slicer, transform the model before, I just added `--rotate`, `--translate` and `--scale` feature in 0.5.2.

**Comment by Spiritdude** [comment]
You only use `--angle=8`, that's very small, can you print 90 degrees overhangs with it? Or do you have other reasons to slice conic (have stronger pieces) - just curious.

**Comment by smokes2345** [comment]
Ok, awesome, i'll have to check out the latest version.

Honestly i just love the idea of *actually using* all three axis and, seeing it now, i'm surprised nobody has tried it before (as in, its not already built into most slicers).  I have to use a small angle because i'm printing on a (mostly) stock ender 3 with a hero me gen3, so no RTN for me lol.  at that low angle 90 degree overhangs are still rough, but only slightly more so than if i was using supports.  I also noticed you prefer cura, where i'm using prusaslicer.  the default profiles for the ender 3 in prusa are much better than anything i was using in cura, so i switched about a year ago and have never looked back, maybe i should lol.  but yes, i also like using conical slices for the layer adhesion, conical slices == greater surface area == more adhesion.

**Comment by Spiritdude** [comment]
@smokes2345 thanks for the feedback, yes indeed, I think it has many advantages even with 3-axis FDM printers, I managed to print with 25 degrees, but just 2mm thick segments (for my use case); another guy managed to print with 45 degrees with part cooler moved up, with a CR10 nozzle setup (not sure how it relates to Ender 3 setup). If you like to continue exchange with me perhaps better per email (contactATxyzdimsDOTcom).
