### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory 

### ISSUE THREAD

**Issue by jesusarmin** [Spiritdude/Slicer4RTN#6]
hello greetings to all from mexico

When I try to run a test I get the message: FileNotFoundError: [Errno 2] No such file or directory 
![222](https://user-images.githubusercontent.com/115727277/203900578-64ac955f-a5a6-431b-aae7-300f87007231.png)

I have tried to find a solution but I can't find one... could someone help me?

**Comment by Spiritdude** [comment]
You reported in the wrong repo, my code is written in Perl, yours in Python. It looks like CNC Kitchen's fork or so.
