### ISSUE TITLE
stl2rtn and gcodertn

### ISSUE THREAD

**Issue by broslab** [Spiritdude/Slicer4RTN#7]
Can you send me a Slicer4RTN v0.0.2 ?
when it still consisted of stl2rtn and gcodertn.

**Comment by Spiritdude** [comment]
The code I didn't track with `git`, so it's gone as separate scripts. All functionality is now in the `slicer4rtn` direct:
- load mesh
- project mesh conical
- slice planar
- undo conical projection of gcode coords
