### ISSUE TITLE
How do I even install this or use it?

### ISSUE THREAD

**Issue by mikedattolo** [Spiritdude/Slicer4RTN#8]
How does someone go about using this? Do I need to download a program and install it through it, I have no clue about how to go about installing or using this, can you explain how or make a video tutorial on how to use it?

**Comment by mikedattolo** [comment]
hello?

**Comment by mikedattolo** [comment]
Hello? I have no clue how to go about this, can you make a video tutorial or something plzzz

**Comment by Spiritdude** [comment]
Read https://github.com/Spiritdude/Slicer4RTN without skipping any part, because I describe how to install and use it there, additionally it contains links to my web-site where I also describe it even in greater detail.
